#!/bin/sh
before_diff_bytes=`git diff | wc -c`
diff_files=(`git diff --name-only HEAD ./`)

for diff_file in "${diff_files[@]}"
do
    if [[ $diff_file =~ \.go$ ]]; then
        diff_file=`echo $diff_file | sed -e "s/server\///"`
        docker exec dchat-server go fmt $diff_file
    fi
done

after_diff_bytes=`git diff | wc -c`

diff_bytes=`expr $after_diff_bytes \- $before_diff_bytes`
if [[ $diff_bytes > 0 ]] ; then
    echo "Check golang code format!"
    echo "Please git add & git commit again!"
    exit 1
fi
